### ISSUE TITLE
try to run quantize.py but get error CUDA out of memory

### ISSUE THREAD

**Issue by ysanimals** [yxli2123/LoftQ#2]
When I try to use quantize.py to quantize llama2，I use num_bits=4, and other configurations are default, but I get the error of CUDA out of memory at quantize layer 18, what's wrong with this?  My GPU is nvidia-A100 80GB, then I change the num_bits to 2 and 8, it will fast broken at layer 0. Anything wrong about these problems
`model.model.layers.18.mlp.up_proj Linear(in_features=4096, out_features=11008, bias=False)
['T_destination', '__annotations__', '__call__', '__class__', '__constants__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_backward_hooks', '_buffers', '_call_impl', '_forward_hooks', '_forward_pre_hooks', '_get_backward_hooks', '_get_name', '_is_full_backward_hook', '_is_hf_initialized', '_load_from_state_dict', '_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_maybe_warn_non_full_backward_hook', '_modules', '_named_members', '_non_persistent_buffers_set', '_parameters', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_replicate_for_data_parallel', '_save_to_state_dict', '_slow_forward', '_state_dict_hooks', '_version', 'add_module', 'apply', 'bfloat16', 'bias', 'buffers', 'children', 'cpu', 'cuda', 'double', 'dump_patches', 'eval', 'extra_repr', 'float', 'forward', 'get_buffer', 'get_extra_state', 'get_parameter', 'get_submodule', 'half', 'in_features', 'ipu', 'load_state_dict', 'modules', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'out_features', 'parameters', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 'register_forward_pre_hook', 'register_full_backward_hook', 'register_load_state_dict_post_hook', 'register_module', 'register_parameter', 'requires_grad_', 'reset_parameters', 'set_extra_state', 'share_memory', 'state_dict', 'to', 'to_empty', 'train', 'training', 'type', 'weight', 'xpu', 'zero_grad']
asymmetric NormalFloat
asymmetric NormalFloat
Traceback (most recent call last):
  File "quantize.py", line 143, in <module>
    main(args)
  File "quantize.py", line 105, in main
    utils.replace_module(
  File "/data/juicefs_sharing_data/11164126/py-proj/loftQ/LoftQ/utils.py", line 392, in replace_module
    replace_module(immediate_child_module,
  File "/data/juicefs_sharing_data/11164126/py-proj/loftQ/LoftQ/utils.py", line 392, in replace_module
    replace_module(immediate_child_module,
  File "/data/juicefs_sharing_data/11164126/py-proj/loftQ/LoftQ/utils.py", line 392, in replace_module
    replace_module(immediate_child_module,
  [Previous line repeated 1 more time]
  File "/data/juicefs_sharing_data/11164126/py-proj/loftQ/LoftQ/utils.py", line 367, in replace_module
    qlinear_lora.initial_backbone(weight)
  File "/data/juicefs_sharing_data/11164126/py-proj/loftQ/LoftQ/utils.py", line 278, in initial_backbone
    self.qweight, self.absmax, _ = self.quantizer.quantize_block(weight)
  File "/data/juicefs_sharing_data/11164126/py-proj/loftQ/LoftQ/utils.py", line 174, in quantize_block
    qweight = torch.argmin(abs_diff, dim=-1)  # (L, B)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 688.00 MiB (GPU 0; 79.35 GiB total capacity; 77.40 GiB already allocated; 555.12 MiB free; 77.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by ysanimals** [comment]
by the way, my configuration is default     parser.add_argument('--num_bits', type=float, default=4)
    parser.add_argument('--reduced_rank', type=int, default=64)
    parser.add_argument('--num_iter', type=int, default=0)
    parser.add_argument('--fake_quantization', action='store_true')

**Comment by BaohaoLiao** [comment]
> by the way, my configuration is default parser.add_argument('--num_bits', type=float, default=4) parser.add_argument('--reduced_rank', type=int, default=64) parser.add_argument('--num_iter', type=int, default=0) parser.add_argument('--fake_quantization', action='store_true')

Not a solution to your issue. But should we set num_iter=1?

**Comment by BaohaoLiao** [comment]
Similar issue.

I run it this way on an A100 40G GPU: `python quantize.py --num_iter 1`. All other arguments stay as default.

The error happens at layer `model.model.layers.2.mlp.gate_proj Linear(in_features=4096, out_features=11008, bias=False)`

**Comment by BaohaoLiao** [comment]
@ysanimals I resolved this issue by using CPU. It's quite fast with CPU, within a few seconds.

**Comment by yxli2123** [comment]
There's something wrong with the `Quantizer` class. It will be resolved soon.

**Comment by yxli2123** [comment]
Hi @BaohaoLiao, we have moved our quantization framework to [PEFT](https://github.com/huggingface/peft/tree/main/examples/loftq_finetuning). You can also follow the instruction in README.md to apply LoftQ.
